### ISSUE TITLE
technical requirements

### ISSUE THREAD

**Issue by nicokoenig** [dreadderino1987/Music_App#1]
- [x] Test Setup
  - [x] Unit Tests (Jest)
  - [x] E2E (Cypress)
- [x] GitHub Actions
  - [x] Automatisierte Checks bei PRs
    - [x] Prettier
    - [x] ESLint 
  - [x] Automatisches Deployment auf Firebase (Rules, Firestore, usw)
- [x] Firebase Emulation
- [x] Pre Commit Hooks für Prettier und ESLint
- [x] Main Branch ist ein Protected Branch

**Comment by sdietrich1987** [comment]
commit git init
